# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import displayer_pb2 as displayer__pb2


class HelperStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTutorialsList = channel.unary_unary(
                '/Helper/GetTutorialsList',
                request_serializer=displayer__pb2.Empty.SerializeToString,
                response_deserializer=displayer__pb2.TutorialsList.FromString,
                )
        self.GetTutorial = channel.unary_unary(
                '/Helper/GetTutorial',
                request_serializer=displayer__pb2.TutorialIndex.SerializeToString,
                response_deserializer=displayer__pb2.Tutorial.FromString,
                )


class HelperServicer(object):
    """Missing associated documentation comment in .proto file"""

    def GetTutorialsList(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTutorial(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HelperServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTutorialsList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTutorialsList,
                    request_deserializer=displayer__pb2.Empty.FromString,
                    response_serializer=displayer__pb2.TutorialsList.SerializeToString,
            ),
            'GetTutorial': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTutorial,
                    request_deserializer=displayer__pb2.TutorialIndex.FromString,
                    response_serializer=displayer__pb2.Tutorial.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Helper', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Helper(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def GetTutorialsList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Helper/GetTutorialsList',
            displayer__pb2.Empty.SerializeToString,
            displayer__pb2.TutorialsList.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTutorial(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Helper/GetTutorial',
            displayer__pb2.TutorialIndex.SerializeToString,
            displayer__pb2.Tutorial.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
